### ISSUE TITLE
Unable to run serenity from Junit

### ISSUE THREAD

**Issue by drokar** [serenity-bdd/serenity-jbehave#10]
In the SerenityReportingRunner.class,    
the following code prevent the StoryReporter to run properly since the description remain empty:

        if (description == null) {
            description = Description.createSuiteDescription(configurableEmbedder.getClass());
            description.getChildren().addAll(getDescriptions());
        }

The Description class return a new ArrayList() when calling getChildren(), so an easy fix will be:

        if (description == null) {
            description = Description.createSuiteDescription(configurableEmbedder.getClass());
            for (Description d: getDescriptions()) {
                description.addChild(d);
            }
        }

**Comment by wakaleo** [comment]
Will be fixed in 1.0.19
