### ISSUE TITLE
HTML tags are getting printed on Serenity Reports

### ISSUE THREAD

**Issue by anujbajaj** [serenity-bdd/serenity-jbehave#100]
Dear Team,

We have switched over to Serenity 1.1.36 & JBehave 1.13.0 & have noticed that HTML tags are getting printed on Serenity Reports. For ex. 

`<font` color="black"><b>Any `Text</b></font>`

Earlier it used to work fine & the sample shared above was printing the text in bold & black color.

Request you to look at it & update.

Regards,
Anuj

**Comment by wakaleo** [comment]
This is an intentional fix to work around the format of some errors in JUnit and Hamcrest assertions, which need tags to be written completely. What is your use case for wanting HTML tags to be rendered in the reports?

**Comment by anujbajaj** [comment]
We have different levels of failure to report such as soft fails, hard fails & warnings & each of these failure levels are associated with different HTML formats to make them easily identifiable in test results report.

**Comment by wakaleo** [comment]
Take a look at http://thucydides.info/docs/articles/semantic-exceptions.html, this might be a better way of doing what you are trying to achieve.

**Comment by wakaleo** [comment]
You can inject markdown syntax into steps by configuring the `enable.markdown` system property like this:

```
enable.markdown=story,narrative,scenario,step
```

**Comment by anujbajaj** [comment]
What is the use of this property. How it is going to effect serenity reports?

**Comment by wakaleo** [comment]
If you set this property, you will be able to format test and step titles using Markdown (https://daringfireball.net/projects/markdown/)

**Comment by anujbajaj** [comment]
Is it possible for you to share an example, please?

I set this property in serenity.properties file & then following the markdown documentation, I tried printing some sample text on bold by using **Sample Text**, however, it didn't help much.

Do we need to add maven markdown plugin or jar for this?

**Comment by anujbajaj** [comment]
`**Sample Text**`

**Comment by anbajaj** [comment]
@wakaleo can you please advise here?

**Comment by wakaleo** [comment]
The Cucumber feature file:
```
Feature: Filtering todos

  In order to make me feel **a sense of accomplishment**
  As a forgetful person
  I want to be to _view all of things I have completed_

  Scenario: View **only completed items** #123
    Given that Jane has a todo list containing Buy some milk, Walk the dog
    And she has completed the task called 'Walk the dog'
    When she filters her list to show only Completed tasks
    Then her todo list should contain Walk the dog
```

In the serenity.properties file:

```
enable.markdown=story,narrative,scenario
```

In the reports:
![image](https://cloud.githubusercontent.com/assets/55986/23414169/e2c9f93c-fdd2-11e6-897b-7cc89b4bd514.png)

**Comment by anbajaj** [comment]
Thanks for sharing this. Does this works with JBehave as well?

**Comment by wakaleo** [comment]
It should do, the reporting doesn't care where the test results come from.

**Comment by anbajaj** [comment]
@wakaleo 

Somehow it is not working on step level. I am using serenity 1.1.40 with JBehave 1.9.0

serenity.properties file:
enable.markdown=story,narrative,scenario,step

INFO("**Testing Markdown**);

@Step
 public void INFO(String message) {
 }

Serenity Report:
INFO: **Testing Markdown**
