### ISSUE TITLE
are serenity.batch.size and serenity.batch.number properties supported for jbehave based project?

### ISSUE THREAD

**Issue by ceacostaGIT** [serenity-bdd/serenity-jbehave#106]
Hi, I thought this was the best place to ask and hopefully get an official answer (or more insight) from @wakaleo or any of the main contributors to the project.  

From other forums and from the test runs on my **jbehave** thucydides/serenity based project, it seems that running tests on batches using the **serenity.batch.size** and **serenity.batch.number** properties do not work as expected but instead run the _entire set_ of scenarios in a jbehave based project.

Are these properties supported in a jbehave/serenity project? If so, what version should I use for my project?

If these properties are not supported, is this something that you have on the serenity roadmap? or do you have an idea on the level of effort that it may require to support them?

Thank you in advance and sorry if this is not the best means for posting this question/request and let me know if there is a better place to post this question/request.

**Comment by wakaleo** [comment]
Batches are only supported in JUnit. The best way to run JBehave stories in parallel is to have separate runners and use the JUnit parallel test support.

**Comment by olyv** [comment]
Just to confirm: is it still not introduced for Cucumber? If so, would it be possible to update documentation with a remark "only supported in JUnit" (http://thucydides.info/docs/serenity-staging/#_running_serenity_tests_in_parallel_batches)?

**Comment by wakaleo** [comment]
We are migrating the documentation to a new platform at the moment, so we will keep that in mind.

**Comment by wevertoncastro** [comment]
@wakaleo "Batches are only supported in JUnit. The best way to run JBehave stories in parallel is to have separate runners and use the JUnit parallel test support."

I would like to know, if you have some example project on how to implement this runner, to run jbehave / serentiy (stories) in batch / parallel.

**Comment by wakaleo** [comment]
As this is a question, could you post it on http://serenity-bdd.rocket.chat or StackOverflow?
