### ISSUE TITLE
How to do a debug for serenity projects

### ISSUE THREAD

**Issue by Santhosh17** [serenity-bdd/serenity-jbehave#107]
I have created a new project (infact its a default project of serenity). 
![image](https://cloud.githubusercontent.com/assets/6276293/19228338/dd96ac36-8ee1-11e6-8a35-5f7dd1ddb222.png)
Screenshot 1

![image](https://cloud.githubusercontent.com/assets/6276293/19228555/f95ebda8-8ee3-11e6-9c60-76ab2d121bb0.png)
Screenshot 2

in the maven run configuration i have only added 
clean verify 
This runs the project without any issue
but i want to debug the code in eclipse at the added breakpoint (as in screenshot 1)
is there any configuration i need to add to the maven run configurations so as to debug the serenity projects.

**Comment by wakaleo** [comment]
As this is a usage question and not an issue, could you please ask it on StackOverflow with the serenity-bdd tag, so that the answer can benefit more users?

**Comment by dan0935** [comment]
I am also having  same issue,can you suggest any solution?
