### ISSUE TITLE
How to i generate serenity reports with jbehave we migrated from thucydides - Question

### ISSUE THREAD

**Issue by prathimak** [serenity-bdd/serenity-jbehave#108]
Hi,

Is there any document to generate reports in serenity we migrated from thucydides but still reports are generating in thucydides in jenkins, i found this plugin in google https://wiki.jenkins-ci.org/display/JENKINS/Serenity+Plugin can i use this or is there any other way.

Thanksinadvance

**Comment by wakaleo** [comment]
Hi,

Since this is a question and not an issue, could you please ask it on StackOverflow with the tag #serenity-bdd, so that a broader audience can benefit from the answers?

**Comment by prathimak** [comment]
ok i would do that thank you
