### ISSUE TITLE
Default value for getStoryTimeoutInSecs method in SerenityReportingRunner

### ISSUE THREAD

**Issue by azhur** [serenity-bdd/serenity-jbehave#11]
The method  getStoryTimeoutInSecs in SerenityReportingRunner:
```java
protected int getStoryTimeoutInSecs() {
   return environmentVariables.getPropertyAsInteger(SerenityJBehaveSystemProperties.STORY_TIMEOUT_IN_SECS.getName(), 300);
}
```

use 300 as default value.
It would be nice to use ``` getConfiguredEmbedder().embedderControls().storyTimeoutInSecs() ``` as default value. So this way you can set this property in your code without using the environment variable.

**Comment by wakaleo** [comment]
Done - it will be in the next release.

On 8 April 2015 at 19:58, Artur Zhurat <notifications@github.com> wrote:

> The method getStoryTimeoutInSecs in SerenityReportingRunner:
>
> protected int getStoryTimeoutInSecs() {
>    return environmentVariables.getPropertyAsInteger(SerenityJBehaveSystemProperties.STORY_TIMEOUT_IN_SECS.getName(), 300);
> }
>
> use 300 as default value.
> It would be nice to use
> getConfiguredEmbedder().embedderControls().storyTimeoutInSecs() as
> default value. So this way you can set this property in your code without
> using the environment variable.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-jbehave/issues/11>.
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

The dates for the 2014 BDD workshops have been scheduled! Check out our
upcoming *BDD/TDD Master classes*
<http://wakaleo.com/training/testing-and-tdd-for-java-developers> and
our *Advanced
BDD Requirements Workshops
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, coming
soon to *Sydney
<http://wakaleo.com/training/testing-and-tdd-for-java-developers/public-courses>
*
and *Melbourne
<http://wakaleo.com/training/testing-and-tdd-for-java-developers/public-courses>!*
___________________________________________________

**Comment by YamStranger** [comment]
Hello @azhur 

This update already published, please check it in latest version of jbehave

Thanks!!!
