### ISSUE TITLE
The JBehave step remain in "Pending" state if the corresponding method in JbehaveSteps class is not found. 

### ISSUE THREAD

**Issue by ak120684** [serenity-bdd/serenity-jbehave#110]
A compilation error or run time error should be thrown rather than have the step in Pending state.
For ex: I ran into this real scenario.
I had the first step in my story file as below.

"Given I am on mobile site xyz.com"

That step had corresponding jbehave step class which i missed pushing in the repo. And so, it wasnt picked up in the runs over my CI server and since it was the first step in the test, all other consequent steps were ignored. The test-report  kept showing the first step as pending and i was clueless for hours thinking why the tests run on my local fine and not on the CI server. 

it was by fluke i happened to look at my unversioned files on my local machine and noticed why the jbehave step class file is showing in that list.

Should it have complained instead of showing as pending state, it would have been way easier to fix :)

**Comment by wakaleo** [comment]
This is the intended behaviour of JBehave, and Serenity has little control over how JBehave acts at this level.
