### ISSUE TITLE
Always get "TEST PENDING" when using external data table

### ISSUE THREAD

**Issue by ladamiak** [serenity-bdd/serenity-jbehave#112]
I'm trying to use an external table for data as described in JBehave site:
http://jbehave.org/reference/stable/parametrised-scenarios.html

Like this:

```
Given a stock of <valorUm> and a <valorDois>
When the stock is traded at location
Then the alert status should be xstatus
 
Examples: 
org/jbehave/examples/trader/stories/trades.table  
```

The problem is that when I execute this tests Serenity always give me the "TEST PENDING" messagem.

If I change it for an ordinary examples table, like the one below, everything runs fine:
```
|valorUm,valorDois|
|1,318|
|2,5|
|3,6|
|-1,7|

```

Any ideas?

**Comment by wakaleo** [comment]
Try putting this in the constructor of your SerenityStory (or SerenityStories)-derived class:
```
        configuration().useStoryParser(new RegexStoryParser(new ExamplesTableFactory(new LoadFromClasspath(this.getClass()))))
```

**Comment by ladamiak** [comment]
I did just that and still got the error, then I just realized that the
separators on the csv file should be pipes "|".

Changing coma to pipes did the trick.

Em 28 de nov de 2016 17:35, "John Ferguson Smart" <notifications@github.com>
escreveu:

**Comment by ladamiak** [comment]
Just for closing,
Using a csv file like the one bellow did worked for me:
```
valorUm|valorDois|valor tres
1|34|3333333
5|43|3333333
3|12|3333333
2|4|3333333
```
