### ISSUE TITLE
Crash on logging from @BeforeStory

### ISSUE THREAD

**Issue by richard-melvin** [serenity-bdd/serenity-jbehave#116]
Real case is more complex, but can be simply reproduced. I have a steps class with:

```java
  @Steps
  private MyLog log;

  @BeforeStory
  public void runBeforeStory()
  {
    log.describe("hello world");
```

where 'describe' is  an empty method of MyLog annotated with @Step.

This crashes with the stack trace below, 

Preconditions.checkState(boolean) line: 159	
BaseStepListener.getCurrentTestOutcome() line: 242	
BaseStepListener.recordStepToCurrentTestOutcome(TestStep) line: 416	
BaseStepListener.recordStep(ExecutedStepDescription) line: 410	
BaseStepListener.stepStarted(ExecutedStepDescription) line: 385	
StepEventBus.stepStarted(ExecutedStepDescription) line: 278	
StepInterceptor.notifyStepStarted(Object, Method, Object[]) line: 438	
StepInterceptor.testStepResult(Object, Method, Object[], MethodProxy) line: 129	
StepInterceptor.intercept(Object, Method, Object[], MethodProxy) line: 57	
MyLog$$EnhancerByCGLIB$$874f015b.describe(String) line: not available	
MyClass.runBeforeStory() line: 68

**Comment by wakaleo** [comment]
This is certainly a bug. But what outcome are you expecting? If you invoke a step method before a story has started, there is nowhere for it to be recorded to.

**Comment by richard-melvin** [comment]
I'd be happy if it executed without crashing. In the real code, it is some common code that usually want to log the extra info, but doesn't care if doesn't for the default startup case. With everything being done by annotations and CGILIB rewriting, there is no obvious way to make the logging conditional on where it's needed.

Alternatively, if there was some cleaner way of getting information into the test log without using annotation magic, that would be preferable.

**Comment by wakaleo** [comment]
Should work in the latest version.
