### ISSUE TITLE
Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.19.1:verify (default) on project BDDContabilidadCenter: There are test failures.

### ISSUE THREAD

**Issue by dannybarrientos** [serenity-bdd/serenity-jbehave#120]
Good morning!!!
I get this error in Jenkins, when my tests are run.
The tests run on a windows machine.
**How do I solve this problem??**

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.19.1:verify (default) on project BDDContabilidadCenter: There are test failures.
[ERROR] 
[ERROR] Please refer to D:\jenkins-slave-Serenity\workspace\Universidad\ContabilidadCenter\1_Desarrollo\ContabilidadCenter-PruebasAceptacionDllo\target\failsafe-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Build step 'Invoke top-level Maven targets' marked build as failure
Build step 'Invoke top-level Maven targets' marked build as failure
[htmlpublisher] Archiving HTML reports...

Thank for your attention!! :)
Regards!!

**Comment by wakaleo** [comment]
It says that "There are test failures", so maybe there are test failures?

**Comment by dannybarrientos** [comment]
Thanks for your answer.
But we can not see the report



![image](https://cloud.githubusercontent.com/assets/8796408/24512474/49e2d58a-1534-11e7-8896-4eacbcccf6b8.png)

**Comment by wakaleo** [comment]
It's hard to troubleshoot with the information here - can you provide a sample project that reproduces the issue?

**Comment by dannybarrientos** [comment]
The problem is that it is not easy to reproduce. Because locally the report shows well. However in jenkins is where we have that problem.

regards

**Comment by wakaleo** [comment]
Try to check for exceptions elsewhere in the Jenkins log.

**Comment by dannybarrientos** [comment]
This is my log
regards

> (AfterStories)

[pool-2-thread-2] INFO net.thucydides.core.reports.html.HtmlAcceptanceTestReporter - NOTE: I couldn't convert scaled screenshot for f446644821c9281bbc83a60878d1f0a7.png: target\site\serenity\scaled_f446644821c9281bbc83a60878d1f0a7.png: The process cannot access the file because it is being used by another process.

java.nio.file.FileSystemException: target\site\serenity\scaled_f446644821c9281bbc83a60878d1f0a7.png: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileCopy.copy(WindowsFileCopy.java:165)
	at sun.nio.fs.WindowsFileSystemProvider.copy(WindowsFileSystemProvider.java:278)
	at java.nio.file.Files.copy(Files.java:1227)
	at net.thucydides.core.images.ResizableImage.saveTo(ResizableImage.java:144)
	at net.thucydides.core.reports.html.screenshots.ScreenshotFormatter.resizedImage(ScreenshotFormatter.java:65)
	at net.thucydides.core.reports.html.screenshots.ScreenshotFormatter.expandToHeight(ScreenshotFormatter.java:47)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter$ExpandedScreenshotConverter.convert(HtmlAcceptanceTestReporter.java:223)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter$ExpandedScreenshotConverter.convert(HtmlAcceptanceTestReporter.java:208)
	at ch.lambdaj.function.convert.ConverterIterator.next(ConverterIterator.java:37)
	at ch.lambdaj.Lambda.convert(Lambda.java:986)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.expandScreenshots(HtmlAcceptanceTestReporter.java:202)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateScreenshotReportsFor(HtmlAcceptanceTestReporter.java:188)
	at net.thucydides.core.reports.html.HtmlAcceptanceTestReporter.generateReportFor(HtmlAcceptanceTestReporter.java:99)
	at net.thucydides.core.reports.ReportService.generateReportFor(ReportService.java:220)
	at net.thucydides.core.reports.ReportService.access$100(ReportService.java:34)
	at net.thucydides.core.reports.ReportService$1.run(ReportService.java:156)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Generating reports view to 'D:\jenkins-slave-Serenity\workspace\Universidad\Contabilidad\1_Desarrollo\Contabilidad-PruebasAceptacionDllo\target\jbehave' using formats '[stats, console, html, xml, serenityreporter, junitscenarioreporter]' and view properties '{decorateNonHtml=true}'
Reports view generated with 5 stories (of which 0 pending) containing 18 scenarios (of which 0 pending)
Tests run: 16, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 339.701 sec - in com.sura.billing.cuenta.AjusteCobroVencidoRiesgoAnticipado

Results :

Tests in error: 
  JUnit4Provider.invoke:161->executeTestSet:238->executeWithRerun:274->execute:367 » Runtime

Tests run: 99, Failures: 0, Errors: 1, Skipped: 0

[INFO] 
[INFO] --- serenity-maven-plugin:1.1.42:aggregate (serenity-reports) @ BDDContabilidad ---
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Generating HTML Story Reports from D:\jenkins-slave-Serenity\workspace\Universidad\Contabilidad\1_Desarrollo\Contabilidad-PruebasAceptacionDllo\target\site\serenity
Generating HTML Story Reports to D:\jenkins-slave-Serenity\workspace\Universidad\Contabilidad\1_Desarrollo\Contabilidad-PruebasAceptacionDllo\target\site\serenity
GENERATE CUSTOM REPORTS
[INFO] 
[INFO] --- maven-failsafe-plugin:2.19.1:verify (default) @ BDDContabilidad ---
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Skipping BDDContabilidad
[INFO] This project has been banned from the build due to previous failures.
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6:21.372s
[INFO] Finished at: Thu Mar 30 10:28:04 COT 2017
[INFO] Final Memory: 37M/581M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.19.1:verify (default) on project BDDContabilidad: There are test failures.
[ERROR] 
[ERROR] Please refer to D:\jenkins-slave-Serenity\workspace\Universidad\Contabilidad\1_Desarrollo\Contabilidad-PruebasAceptacionDllo\target\failsafe-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Build step 'Invoke top-level Maven targets' marked build as failure
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at PROJECT level D:\jenkins-slave-Serenity\workspace\Universidad\Contabilidad\1_Desarrollo\Contabilidad-PruebasAceptacionDllo\target\site\serenity to /var/opt/jenkins/jenkins-app/jobs/Universidad/jobs/Contabilidad/jobs/1_Desarrollo/jobs/Contabilidad-

**Comment by dannybarrientos** [comment]
The thing is: everytime I build (clean install) i get the following error:

Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.19.1:verify (default) on project BDDContabilidad:

**Comment by wakaleo** [comment]
Windows is locking that file (or those files) for some reason. It could be an anti-virus, or some other process.

**Comment by wakaleo** [comment]
What version are you using?

**Comment by dannybarrientos** [comment]
<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <serenity.version>1.1.42</serenity.version>
        <serenity.jbehave.version>1.13.0</serenity.jbehave.version>
        <junit.version>4.12</junit.version>
        <slf4j.simple.version>1.7.7</slf4j.simple.version>
        <assertj.core.version>3.4.0</assertj.core.version>
        <lambdaj.version>2.3.3</lambdaj.version>
        <jbehave.core.version>4.0.5</jbehave.core.version>
        <serenity.maven.plugin.version>1.1.42</serenity.maven.plugin.version>
        <maven.surefire.plugin>2.19.1</maven.surefire.plugin>
        <maven.failsafe.plugin>2.19.1</maven.failsafe.plugin>
        <maven.compiler.plugin>3.2</maven.compiler.plugin>
        <maven.compiler.plugin.source>1.7</maven.compiler.plugin.source>
        <maven.compiler.plugin.target>1.7</maven.compiler.plugin.target>
        <webdriver.driver>chrome</webdriver.driver>
        <webdriver.chrome.driver>chromedriver.exe</webdriver.chrome.driver>

**Comment by wakaleo** [comment]
Could you try with a more recent version?

**Comment by dannybarrientos** [comment]
A recent version about whic?

**Comment by wakaleo** [comment]
Of Serenity - latest version is 1.2.4

**Comment by dannybarrientos** [comment]
Question, if i update the serenity version , do I have to  update the other versions ? 

Which is the best process to update the versions ?

`<serenity.jbehave.version>1.13.0</serenity.jbehave.version>
<junit.version>4.12</junit.version>
<slf4j.simple.version>1.7.7</slf4j.simple.version>
<assertj.core.version>3.4.0</assertj.core.version>
<lambdaj.version>2.3.3</lambdaj.version>
<jbehave.core.version>4.0.5</jbehave.core.version>
<serenity.maven.plugin.version>1.1.42</serenity.maven.plugin.version>
<maven.surefire.plugin>2.19.1</maven.surefire.plugin>
<maven.failsafe.plugin>2.19.1</maven.failsafe.plugin>
<maven.compiler.plugin>3.2</maven.compiler.plugin>
<maven.compiler.plugin.source>1.7</maven.compiler.plugin.source>
<maven.compiler.plugin.target>1.7</maven.compiler.plugin.target>`

**Comment by dannybarrientos** [comment]
Thank you very much @wakaleo ,
**The solution**
Remove the dependency of jira and I was able to solve the problem for the moment.

`   
        
        <dependency>		
`

**I can generate report of serenity bdd, but it this error still comes out**
**Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.19.1:verify (default) **
