### ISSUE TITLE
Statements in Lifecycle/After in story file are not displayed in report when test case is failed.

### ISSUE THREAD

**Issue by sirius2k** [serenity-bdd/serenity-jbehave#121]
I attached Lifecycle section in story file as following.

Lifecycle:
Before:
After:
Outcome: ANY
Then the test context is cleared

And I found that it is always executed after each test is done. However, result is not displayed in the report whenever test is failed.

I see following in Success case :
Then the test context is cleared SUCCESS	0s

But, I can't see the above result when test is failed, even though it is executed.

**Comment by wakaleo** [comment]
Could you provide some sample code of what you are doing, with the results you are getting and what you would expect?

**Comment by wakaleo** [comment]
Works in 1.31.0
