### ISSUE TITLE
Empty Meta Tags cause the Story Title to become blank in reports

### ISSUE THREAD

**Issue by hazmeister** [serenity-bdd/serenity-jbehave#123]
I was caught out by this after upgrading from -  serenity jbehave version 1.9.0 to 1.24.0

When creating stories in IntelliJ using the JBehave Support plugin, the default template includes an empty Meta tag, like so:

    Meta:

    Narrative:
    As a user
    I want to perform an action
    So that I can achieve a business goal

    Scenario: scenario description
    Given a system state
    When I do something
    Then system is in a different state

Normally, I'm pretty good at stripping these out, but it appears a few of these were sitting benign in my repo until I tried to upgrade Serenity.  After generating the report, the story files with empty Meta tag rendered with no title as so:
![image](https://cloud.githubusercontent.com/assets/11080542/25587700/0c936d0c-2e9d-11e7-9549-d017d8898d41.png)

The simple workaround was to remove the redundant meta tag, but this might cause others out, so I thought I would raise an issue.

**Comment by wakaleo** [comment]
Fixed in 1.31.0
