### ISSUE TITLE
Adding a comment to a scenario stops following steps from executing

### ISSUE THREAD

**Issue by hazmeister** [serenity-bdd/serenity-jbehave#124]
Noticed this change in behaviour after upgrading from - serenity jbehave version 1.9.0 to 1.24.0

I've added a comment to a scenario like so:

    Scenario: Not Sure About Following Up
    !-- This is unintended behaviour, but it occurs in both the web and app, so we want to protect the current behaviour until fixed
    Given I recently applied for a job
    When I am not sure about following up
    And I don't get a job offer
    Then the application will be archived

In Serenity JBehave 1.9.0 the comment would be ignored, and the next line would be read:
![image](https://cloud.githubusercontent.com/assets/11080542/25587907/066022e4-2e9e-11e7-841f-9e618f0b9f24.png)

In Serenity JBehave 1.24.0, the whole scenario is ignored:
![image](https://cloud.githubusercontent.com/assets/11080542/25587935/23fa8e5c-2e9e-11e7-83da-e8640e9b4701.png)

**Comment by wakaleo** [comment]
I believe this is a JBehave issue

**Comment by wakaleo** [comment]
Works correctly in 1.31.0
