### ISSUE TITLE
Serenity Sample Project on the latest version

### ISSUE THREAD

**Issue by anbajaj** [serenity-bdd/serenity-jbehave#125]
Hi Team,

Could you please share a sample serenity project running on latest version (1.24) with latest serenity-jBehave (1.24.0). 

Somehow it is not working from our end. A working pom.xml would suffice.

Any help here would be highly appreciated.

Regards,
Anuj

**Comment by wakaleo** [comment]
See https://github.com/serenity-bdd/serenity-jbehave/tree/master/src/smoketests
