### ISSUE TITLE
@BeforeStories uses separate driver instance

### ISSUE THREAD

**Issue by hazmeister** [serenity-bdd/serenity-jbehave#129]
<serenity.version>1.4.1-rc.7</serenity.version>
    <serenity.jbehave.version>1.26.0-rc.3</serenity.jbehave.version>

I'm trying to reduce my test execution time by reusing the same browser for all my tests.  Previously I was using the `@BeforeStory` annotation in the test suite to maximise the browser (for desktop tests) so the browser would be maximised at the start of each story.

I've since set `properties.setValue(SERENITY_RESTART_BROWSER_FOR_EACH, "NEVER");` to keep the browser and changed the annotation to `@BeforeStories`, as it will only need to maximised once.

After these changes, the browser launches and the window is maximised, but then when the story starts, a second driver instance is opened (unmaximised) and used instead of the prepared driver.

# Example

    package com.workray.jbehave.suites;
    
    import net.serenitybdd.core.SerenitySystemProperties;
    import net.serenitybdd.jbehave.SerenityStories;
    import org.jbehave.core.annotations.BeforeStories;
    
    import static com.workray.TestConfiguration.DEFAULT_URL;
    import static com.workray.model.Device.currentDriver;
    import static com.workray.utilities.SessionHelper.recallMaximiseBrowser;
    import static com.workray.utilities.SessionHelper.rememberDashboardTab;
    import static net.thucydides.core.ThucydidesSystemProperty.SERENITY_RESTART_BROWSER_FOR_EACH;
    import static net.thucydides.core.webdriver.ThucydidesWebDriverSupport.getDriver;
    
    public class AcceptanceTestSuite extends SerenityStories {
    
        @BeforeStories
        public void setup() {
            getDriver().get(DEFAULT_URL);
            rememberDashboardTab();
            boolean wantToMaximise = recallMaximiseBrowser();
            boolean runningOnMobileDevice = currentDriver().equalsIgnoreCase("appium");
            if(!runningOnMobileDevice && wantToMaximise) {
                getDriver().manage().window().maximize();
            }
        }
    
        public AcceptanceTestSuite() {
            SerenitySystemProperties properties = new SerenitySystemProperties();
            properties.setValue(SERENITY_RESTART_BROWSER_FOR_EACH, "NEVER");
            String story = System.getProperty("run.story");
            findStoriesCalled(story);
        }
    }

**Comment by wakaleo** [comment]
I don't think this is doable because of the way JBehave works internally, since the browsers are thread-local and BeforeStories will be run in a separate thread.

**Comment by hazmeister** [comment]
Thanks John,
That explains the behaviour here.  I'll stick to using `@BeforeStory`.
