### ISSUE TITLE
integrate sikuli with serenity (package org.sikuli.script does not exist)

### ISSUE THREAD

**Issue by VIVEKSRM** [serenity-bdd/serenity-jbehave#131]
Hi There , 

We need to integrate sikuli with serenity. My serenity version is 1.4.0 and trying to run in 64-bit Window server 2008 R2 SP1 .
But getting below compilation error : 
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /C:/test/src/main/java/pages/TestPage.java:[3,25] package org.sikuli.script does not exist
[ERROR] /C:/test/src/main/java/pages/TestPage.java:[5,25] package org.sikuli.script does not exist
[ERROR] /C:/test/src/main/java/pages/TestPage.java:[6,25] package org.sikuli.script does not exist
[ERROR] /C:/test/src/main/java/pages/TestPage.java:[14,39] cannot find symbol
  symbol:   class FindFailed
  location: class pages.TestPage
[ERROR] /C:/testsrc/main/java/pages/TestPage.java:[17,13] cannot find symbol
  symbol:   class Screen
  location: class pages.TestPage
  
  
  Can you please help us in resolving this issue , let us know if more info required.

**Comment by wakaleo** [comment]
It looks like you haven't added the sikuli dependency to your project.

**Comment by VIVEKSRM** [comment]
Thanks Wakaleo .

We have added "sikulixapi.jar" file in dependency . Can you please let us know what else we need to do

**Comment by wakaleo** [comment]
This is a build script issue, not a Serenity one, so hard to say. How did you add the dependency to your maven/gradle build file?

**Comment by VIVEKSRM** [comment]
Hi,
Below is how we have added dependency. But it is giving error in POM file. Can you please help

<dependency>
		    <groupId>org.sikuli</groupId>
		    <artifactId>sikuli-core</artifactId>
		    <version>1.0.0</version>
		</dependency>

**Comment by wakaleo** [comment]
Try

```
<dependency>
    <groupId>com.sikulix</groupId>
    <artifactId>sikulixapi</artifactId>
    <version>1.1.0</version>
</dependency>
```
--

**Comment by VIVEKSRM** [comment]
Thanks a lot. It worked
