### ISSUE TITLE
dependency issue with lambdaj

### ISSUE THREAD

**Issue by richard-melvin** [serenity-bdd/serenity-jbehave#135]
Using:

```
      <dependency>
        <groupId>net.serenity-bdd</groupId>
        <artifactId>serenity-jbehave</artifactId>
        <version>1.27.0</version>
      </dependency>
```

and running a test, i get:

```
java.lang.NoClassDefFoundError: ch/lambdaj/function/convert/Converter
	at net.serenitybdd.jbehave.SerenityStories.stepsFactory(SerenityStories.java:85)
	at org.jbehave.core.ConfigurableEmbedder.configuredEmbedder(ConfigurableEmbedder.java:126)
	at net.serenitybdd.jbehave.runners.SerenityReportingRunner.<init>(SerenityReportingRunner.java:68)
```

The [pom] (https://search.maven.org/remotecontent?filepath=net/serenity-bdd/serenity-jbehave/1.27.0/serenity-jbehave-1.27.0.pom) reports 
that com.googlecode.lambdaj:lambdaj:2.3.3 is a dependency, but with 'test' scope. However, the above error indicates it is actually used at run-time by the library, not just in testing it.

Workaround is to add:

```
    <dependency>
      <groupId>com.googlecode.lambdaj</groupId>
      <artifactId>lambdaj</artifactId>
      <version>2.3.3</version>
    </dependency>
```

to the client pom.

**Comment by wakaleo** [comment]
I suspect you have a dependency conflict elsewhere in your pom.xml file, and that you may not actually be using serenity-jbehave 1.27.0. (this latest version doesn't use LambdaJ at all, so the exception doesn't make much sense). Do you get the same error when running Maven from the command line?

**Comment by richard-melvin** [comment]
You are right, was some kind of transient issue.
