### ISSUE TITLE
Selenium Grid with custom driver

### ISSUE THREAD

**Issue by SumantaSarathiChakraborty** [serenity-bdd/serenity-jbehave#136]
If you enable
webdriver.remote.url
&
webdriver.remote.driver
then the custom driver i.e. provided driver is not getting invoked. Could you please help?

To elaborate, I want to execute test in remote grid but I want some custom capabilities(extensions) to be set. How can I do that?

webdriver.remote.url=http://localhost:4444/wd/hub
webdriver.remote.driver = chrome
webdriver.driver = provided
webdriver.provided.type = mydriver
webdriver.provided.mydriver = com.serenity.maven.customdrivers.CustomChromeDriver
serenity.driver.capabilities = mydriver

If I use the above configuration then CustomChromeDriver class is never called!

**Comment by wakaleo** [comment]
This is normal - the CustomerDriver configuration overrides all other configurations. You will need to support the remote driver configuration in the custom driver code (or not use a custom driver)
