### ISSUE TITLE
Maven BUILD SUCCESS while several tests failed

### ISSUE THREAD

**Issue by tomaszuss** [serenity-bdd/serenity-jbehave#139]
I have got the problem with version 1.6.1+ of serenity-core
Given some scenarios have errors
When I run the test with:
`mvn clean verify`
Then maven build should be FAILURE but is not.

I think the reason may be the incorrect counting of junit test results:
```Results :
Tests run: 0, Failures: 0, Errors: 0, Skipped: 0`
```
My environment:
```
user@machinename ~/ws/test $ java -version 
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
```
```
user@machinename ~/ws/test $ mvn -version
 Apache Maven 3.3.9
 Maven home: /usr/share/maven
 Java version: 1.8.0_131, vendor: Oracle Corporation
 Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
 Default locale: pl_PL, platform encoding: UTF-8
 OS name: "linux", version:  "4.4.0-97-generic", arch: "amd64", family: "unix"`
```
I prepared sample project with this bug and attached it: [test.tar.gz](https://github.com/serenity-bdd/serenity-jbehave/files/1420137/test.tar.gz)

**Comment by tomaszuss** [comment]
#

**Comment by wakaleo** [comment]
Did you find a work-around for this Tomasz?

**Comment by tomaszuss** [comment]
Unfortunately not. For npw I'm using 1.6.0.

BTW: of course this issue should be reported in serenity-core but I was tired last night and created in serenity-jbehave. My mistake. @wakaleo Is it possible to move the issue into serenity-core?

**Comment by wakaleo** [comment]
Actually it is good here, it has nothing to do with serenity-core. I won’t be able to look at it until next week, but I can point you in the right direction to write a patch. 

In https://github.com/serenity-bdd/serenity-jbehave/blob/master/src/main/java/net/serenitybdd/jbehave/runners/SerenityReportingRunner.java, the JUnitScenarioReporter is not called during Maven runs. This was a workaround to a defect in the JUnit reporter introduced in recent versions of JBehave, but obviously introduces other issues. See if you can create a PR that allows the JUnitScenarioReporter to work correctly with Maven (start by removing the conditionality)

**Comment by wakaleo** [comment]
For the moment I don't know how to fix this. The original solution was to use the reporter class from https://github.com/valfirst/jbehave-junit-runner, however this library is very buggy and now crashes when used with Maven or Gradle, so is no longer viable. 

Any help welcome.

**Comment by wakaleo** [comment]
This should work in serenity-jbehave 1.31.0.

**Comment by tomaszuss** [comment]
@wakaleo Thx. I will check in spare moment.
