### ISSUE TITLE
Needed webDriverCalls in @AfterScenario after assertException/failed scenario

### ISSUE THREAD

**Issue by spcial** [serenity-bdd/serenity-jbehave#14]
Hi,
I'm actually implementing several scenarios and I'm facing an issue I can't solve myself. As I posted already here http://stackoverflow.com/questions/31473491/selenium-getdriver-is-empty-for-afterscenario-after-assertionerror I can't use any webDriverCalls after a scenario failed. As I found out from John Smart, the test is switched to "Dry-run" after a failure.
So I have to think about other ways to implement a logout if a scenario fails. I always want my scenarios to start with a login.. so this is what i am doing in my @BeforeScenario.. but because of dry-run I am not able to perform a logout in my @AfterScenario. Is there ar way to use webDriverCalls when a scenario fails? The only solution for my problem is, that I have to check in the @BeforeScenario if I'm logged in and if so I have to perform a logout first. But this seems to be a little bit "dirty".

**Comment by wakaleo** [comment]
Why do you need to logout after the test fails, knowing that the browser
(and browser session) will be closed at the end of the scenario?

On 20 July 2015 at 18:13, spcial <notifications@github.com> wrote:

> Hi,
> I'm actually implementing several scenarios and I'm facing an issue I
> can't solve myself. As I posted already here
> http://stackoverflow.com/questions/31473491/selenium-getdriver-is-empty-for-afterscenario-after-assertionerror
> I can't use any webDriverCalls after a scenario failed. As I found out from
> John Smart, the test is switched to "Dry-run" after a failure.
> So I have to think about other ways to implement a logout if a scenario
> fails. I always want my scenarios to start with a login.. so this is what i
> am doing in my @BeforeScenario.. but because of dry-run I am not able to
> perform a logout in my @AfterScenario. Is there ar way to use
> webDriverCalls when a scenario fails? The only solution for my problem is,
> that I have to check in the @BeforeScenario if I'm logged in and if so I
> have to perform a logout first. But this seems to be a little bit "dirty".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-jbehave/issues/14>.
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +61 407 247 642
Optimizing your software development process
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

We love breaking down silos and helping smart teams collaborate better! Ask
about our tailored on-site workshops in *Agile Requirements Discovery
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Behaviour
Driven Development
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Agile
Development Practices
<http://wakaleo.com/training/testing-and-tdd-for-java-developers>*, and *Test
Automation
<http://wakaleo.com/training/automated-web-testing-with-webdriver-and-thucydides>*
!
___________________________________________________

**Comment by spcial** [comment]
Thanks for your fast response. My scenarios were always running within the same session, so after a scenario the user is still logged in.  But I found out from a former thucydides-issue report that I can restart the browser and delete the session with "restart.browser.each.scenario". 
I actually haven't seen this in the documentation.
I think I can use this for my test scenarios as I don't need to logout anymore. 
Thank you still for the efforts :+1:
