### ISSUE TITLE
Unable to User LifeCycle: and Before with Examples:

### ISSUE THREAD

**Issue by murthysp** [serenity-bdd/serenity-jbehave#140]
I am trying to implement login functionality in Lifecycle and Before but I am unable to do it. they are marking as pending.   Any help would be highly appreciated.

**Comment by wakaleo** [comment]
Actions in  Before stages should be executed normally. Could you provide a sample project?

**Comment by wakaleo** [comment]
Actions in  Before stages should be executed normally. Could you provide a sample project?

**Comment by murthysp** [comment]
LifeCycle:
Before:
Given the user is on the Application  login page
When the user enters "<username>" AND "<password>"
Then they should login AND see the Home Page
Examples:
|username|password|
|pothukuchi|Password123|


I am trying to run the above scenario before each scenario and it is not executing.

**Comment by wakaleo** [comment]
You are using a data-driven scenario in a Before clause, which is very odd.

In fact, it is a huge anti-pattern to reuse entire scenarios this way. A better approach is to have a single line such as 

```
Given Sally is logged on to the Home Page
```

**Comment by murthysp** [comment]
Thanks a lot wakaleo for your help.
