### ISSUE TITLE
Reading different properties file for different environments 

### ISSUE THREAD

**Issue by murthysp** [serenity-bdd/serenity-jbehave#143]
I am trying to run my test on different environments by reading from properties file by maven command as mentioned in one of the posts 
mvn verify -Pproperties=qa.properties

but I' m getting the following error. Do I need to add any dependencies to pom file.? 

[WARNING] The requested profile "properties=qa.properties" could not be activated because it does not exist.

**Comment by wakaleo** [comment]
-P is the maven command to activate a maven profile. What you need to do is:
```
mvn verify -Dproperties=qa.properties
```

**Comment by murthysp** [comment]
Thanks, Wakaleo Perfectly worked for me.

**Comment by murthysp** [comment]
Another question @wakaleo, How I can read the maven parameter in my java code. Do I need to use TestNg or is there any other way. You suggestion greatly appreciated.
