### ISSUE TITLE
Error "java.lang.IncompatibleClassChangeError: Expected static method "

### ISSUE THREAD

**Issue by Pieber** [serenity-bdd/serenity-jbehave#145]
Hi!

I got the following error messages when running:

> [INFO] Scanning for projects...
> [INFO] 
> [INFO] ------------------------------------------------------------------------
> [INFO] Building mvn-aqb-selenium-serenity 0.0.1-SNAPSHOT
> [INFO] ------------------------------------------------------------------------
> [INFO] 
> [INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ mvn-aqb-selenium-serenity ---
> [INFO] Deleting C:\Users\LEROUXP\workspaces\Oxygen1a\mvn-aqb-selenium-serenity\target
> [INFO] 
> [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ mvn-aqb-selenium-serenity ---
> [INFO] Using 'UTF-8' encoding to copy filtered resources.
> [INFO] Copying 0 resource
> [INFO] 
> [INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ mvn-aqb-selenium-serenity ---
> [INFO] Nothing to compile - all classes are up to date
> [INFO] 
> [INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ mvn-aqb-selenium-serenity ---
> [INFO] Using 'UTF-8' encoding to copy filtered resources.
> [INFO] Copying 5 resources
> [INFO] 
> [INFO] --- maven-compiler-plugin:3.7.0:testCompile (default-testCompile) @ mvn-aqb-selenium-serenity ---
> [INFO] Changes detected - recompiling the module!
> [INFO] Compiling 15 source files to C:\Users\LEROUXP\workspaces\Oxygen1a\mvn-aqb-selenium-serenity\target\test-classes
> [INFO] /C:/Users/LEROUXP/workspaces/Oxygen1a/mvn-aqb-selenium-serenity/src/test/java/fr/ag2rlamondiale/aqb/selenium/page/AqbPage.java: Some input files use or override a deprecated API.
> [INFO] /C:/Users/LEROUXP/workspaces/Oxygen1a/mvn-aqb-selenium-serenity/src/test/java/fr/ag2rlamondiale/aqb/selenium/page/AqbPage.java: Recompile with -Xlint:deprecation for details.
> [INFO] 
> [INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ mvn-aqb-selenium-serenity ---
> [INFO] 
> [INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ mvn-aqb-selenium-serenity ---
> [INFO] Building jar: C:\Users\LEROUXP\workspaces\Oxygen1a\mvn-aqb-selenium-serenity\target\mvn-aqb-selenium-serenity-0.0.1-SNAPSHOT.jar
> [INFO] 
> [INFO] --- maven-failsafe-plugin:2.20.1:integration-test (default) @ mvn-aqb-selenium-serenity ---
> [INFO] 
> [INFO] -------------------------------------------------------
> [INFO]  T E S T S
> [INFO] -------------------------------------------------------
> [INFO] Running fr.ag2rlamondiale.aqb.selenium.features.WhenAcceptanceIT
> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> SLF4J: Defaulting to no-operation (NOP) logger implementation
> SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
> Processing system properties {}
> Using controls EmbedderControls[batch=false,skip=false,generateViewAfterStories=true,ignoreFailureInStories=false,ignoreFailureInView=true,verboseFailures=false,verboseFiltering=false,storyTimeouts=1000,threads=1,failOnStoryTimeout=false]
> 
> (BeforeStories)
> 
> Running story stories/aqb/aqb.story
> 
> (stories/aqb/aqb.story)
> Narrative:
> In order to access the Agdrlamondiale services
> As a n already registered customer
> I want to connect to my customer space Vision360 account
> Story name for stories/aqb/aqb.story => TestTag{name='Aqb/Aqb', type='story'}
> Using timeout for story aqb.story of 1000 secs.
> Story name for stories/aqb/aqb.story => TestTag{name='Aqb/Aqb', type='story'}
> Scenario: check if the http requests from google analytics
> Examples:
> Given on the main page of Aqb customer space <username> <password>
> When is on the warranties page
> 
> |username|password|
> |67ha8p|angel2016|
> 
> Example: {username=67ha8p, password=angel2016}
> Given on the main page of Aqb customer space 67ha8p angel2016 (FAILED)
> (java.lang.IncompatibleClassChangeError: Expected static method net.thucydides.core.steps.StepAnnotations.injectScenarioStepsInto(Ljava/lang/Object;Lnet/thucydides/core/steps/StepFactory;)V)
> When is on the warranties page (NOT PERFORMED)
> 
> 
> java.lang.IncompatibleClassChangeError: Expected static method net.thucydides.core.steps.StepAnnotations.injectScenarioStepsInto(Ljava/lang/Object;Lnet/thucydides/core/steps/StepFactory;)V
> 	at net.serenitybdd.jbehave.SerenityStepFactory.createInstanceOfType(SerenityStepFactory.java:82)
> 	at org.jbehave.core.steps.StepCreator.stepsInstance(StepCreator.java:93)
> 	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:733)
> 	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:346)
> ...
> 
> 
> (AfterStories)
> 
> Generating reports view to 'C:\Users\LEROUXP\workspaces\Oxygen1a\mvn-aqb-selenium-serenity\target\jbehave' using formats '[stats, console, html, xml, serenityreporter, junitscenarioreporter]' and view properties '{decorateNonHtml=true}'
> Reports view generated with 2 stories (of which 0 pending) containing 1 scenarios (of which 0 pending)
> Failures in reports view: 1 scenarios failed
> [ERROR] Tests run: 7, Failures: 2, Errors: 2, Skipped: 1, Time elapsed: 5.606 s <<< FAILURE! - in fr.ag2rlamondiale.aqb.selenium.features.WhenAcceptanceIT
> [ERROR] Given on the main page of Aqb customer space <username> <password>(fr.ag2rlamondiale.aqb.selenium.features.steps.AqbStepDefinitions)  Time elapsed: 0.01 s  <<< ERROR!
> java.lang.IncompatibleClassChangeError: Expected static method net.thucydides.core.steps.StepAnnotations.injectScenarioStepsInto(Ljava/lang/Object;Lnet/thucydides/core/steps/StepFactory;)V
> 
> [ERROR] Scenario: check if the http requests from google analytics  Time elapsed: 0.021 s  <<< FAILURE!
> java.lang.AssertionError: scenario failed!
> 
> [ERROR] aqb.story  Time elapsed: 0.18 s  <<< FAILURE!
> java.lang.AssertionError: story failed!
> 
> [ERROR] fr.ag2rlamondiale.aqb.selenium.features.WhenAcceptanceIT  Time elapsed: 3.806 s  <<< ERROR!
> java.lang.RuntimeException: 
> org.jbehave.core.embedder.Embedder$RunningStoriesFailed: Failures in running stories: 
> org.jbehave.core.embedder.PerformableTree$SomethingHappened@8dfdb8: java.lang.IncompatibleClassChangeError: Expected static method net.thucydides.core.steps.StepAnnotations.injectScenarioStepsInto(Ljava/lang/Object;Lnet/thucydides/core/steps/StepFactory;)V
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:369)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:275)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:239)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:160)
> Caused by: org.jbehave.core.embedder.Embedder$RunningStoriesFailed: 
> Failures in running stories: 
> org.jbehave.core.embedder.PerformableTree$SomethingHappened@8dfdb8: java.lang.IncompatibleClassChangeError: Expected static method net.thucydides.core.steps.StepAnnotations.injectScenarioStepsInto(Ljava/lang/Object;Lnet/thucydides/core/steps/StepFactory;)V
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:369)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:275)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:239)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:160)
> 
> [INFO] 
> [INFO] Results:
> [INFO] 
> [ERROR] Failures: 
> [ERROR]   scenario failed!
> [ERROR]   story failed!
> [ERROR] Errors: 
> [ERROR]   AqbStepDefinitions.Given on the main page of Aqb customer space <username> <password> » IncompatibleClassChange
> [ERROR]   JUnit4Provider.invoke:160->executeTestSet:239->executeWithRerun:275->execute:369 » Runtime
> [INFO] 
> [ERROR] Tests run: 7, Failures: 2, Errors: 2, Skipped: 1
> [INFO] 
> [INFO] 
> [INFO] --- serenity-maven-plugin:1.8.1:aggregate (serenity-reports) @ mvn-aqb-selenium-serenity ---
> [INFO] current_project.base.dir: C:\Users\LEROUXP\workspaces\Oxygen1a\mvn-aqb-selenium-serenity
> [INFO] Generating test results for 1 tests
> [INFO] 4 requirements loaded after 108 ms
> [INFO] 4 related requirements found after 108 ms
> [INFO] Generating test outcome reports: false
> [INFO] Starting generating reports: 128 ms
> [INFO] Configured report threads: 20
> [INFO] Test results for 1 tests generated in 789 ms
> [INFO] 
> [INFO] --- maven-failsafe-plugin:2.20.1:verify (verify) @ mvn-aqb-selenium-serenity ---
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 16.324 s
> [INFO] Finished at: 2017-11-30T09:17:45+01:00
> [INFO] Final Memory: 35M/85M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.20.1:verify (verify) on project mvn-aqb-selenium-serenity: There are test failures.
> [ERROR] 
> [ERROR] Please refer to C:\Users\LEROUXP\workspaces\Oxygen1a\mvn-aqb-selenium-serenity\target\failsafe-reports for the individual test results.
> [ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
> [ERROR] -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

This error appeared after I upgraded the dependencies. Here is my pom.xml file:

> <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
> 	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
> 	<modelVersion>4.0.0</modelVersion>
> 	
> 	<artifactId>mvn-aqb-selenium-serenity</artifactId>
> 	<groupId>fr.ag2rlamondiale</groupId>
> 	<version>0.0.1-SNAPSHOT</version>
> 	<properties>
> 		<browsermob-proxy.version>2.1.5</browsermob-proxy.version>
> 		<joda.time.version>2.9.9</joda.time.version>
> 		<maven.compiler.plugin.version>3.7.0</maven.compiler.plugin.version>
> 		<maven.failsafe.plugin.version>2.20.1</maven.failsafe.plugin.version>
> 		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
> 		<serenity.version>1.8.1</serenity.version>
> 		<serenity.jbehave.version>1.24.0</serenity.jbehave.version>
> 		<serenity.maven.version>1.8.1</serenity.maven.version>
> 	</properties>
> 	
> 	<dependencies>
> 		
> 		<dependency>
> 			<groupId>net.serenity-bdd</groupId>
> 			<artifactId>serenity-jbehave</artifactId>
> 			<version>${serenity.jbehave.version}</version>
> 		</dependency>
> 
> 		
> 		<dependency>
> 			<groupId>net.serenity-bdd</groupId>
> 			<artifactId>serenity-core</artifactId>
> 			<version>${serenity.version}</version>
> 		</dependency>
> 
> 		
> 		<dependency>
> 			<groupId>net.serenity-bdd</groupId>
> 			<artifactId>serenity-report-resources</artifactId>
> 			<version>${serenity.version}</version>
> 		</dependency>
> 		
> 		
> 		<dependency>
>     		<groupId>joda-time</groupId>
>     		<artifactId>joda-time</artifactId>
>     		<version>${joda.time.version}</version>
> 		</dependency>
> 		
> 		
> 		<dependency>
>     		<groupId>net.lightbody.bmp</groupId>
>     		<artifactId>browsermob-core</artifactId>
>     		<version>${browsermob-proxy.version}</version>
> 		</dependency>
> 	</dependencies>
> 	<build>
> 		<plugins>
> 			<plugin>
> 				<groupId>org.apache.maven.plugins</groupId>
> 				<artifactId>maven-compiler-plugin</artifactId>
> 				<version>${maven.compiler.plugin.version}</version>
> 				<configuration>
> 					<source>1.6</source>
> 					<target>1.6</target>
> 					<encoding>UTF-8</encoding>
> 				</configuration>
> 			</plugin>
> 
> 			<plugin>
> 				<groupId>org.apache.maven.plugins</groupId>
> 				<artifactId>maven-failsafe-plugin</artifactId>
> 				<version>${maven.failsafe.plugin.version}</version>
> 				<executions>
> 					<execution>
> 						<goals>
> 							<goal>integration-test</goal>
> 						</goals>
> 					</execution>
> 					<execution>
> 						<id>verify</id>
> 						<phase>verify</phase>
> 						<goals>
> 							<goal>verify</goal>
> 						</goals>
> 					</execution>
> 				</executions>
> 				<configuration>
> 					<systemProperties>
> 						<surefire.rerunFailingTestsCount>${surefire.rerunFailingTestsCount}</surefire.rerunFailingTestsCount>
> 						<surefire.rerunFailingTestsCount>${surefire.rerunFailingTestsCount}</surefire.rerunFailingTestsCount>
> 					</systemProperties>
> 				</configuration>
> 			</plugin>
> 			<plugin>
> 				<groupId>net.serenity-bdd.maven.plugins</groupId>
> 				<artifactId>serenity-maven-plugin</artifactId>
> 				<version>${serenity.maven.version}</version>
> 				<dependencies>
> 					<dependency>
> 						<groupId>net.serenity-bdd</groupId>
> 						<artifactId>serenity-core</artifactId>
> 						<version>${serenity.version}</version>
> 					</dependency>
> 				</dependencies>
> 
> 				<executions>
> 					<execution>
> 						<id>serenity-reports</id>
> 						<phase>post-integration-test</phase>
> 						<goals>
> 							<goal>aggregate</goal>
> 						</goals>
> 					</execution>
> 				</executions>
> 			</plugin>
> 		</plugins>
> 	</build>
> </project>

**Comment by wakaleo** [comment]
Use the latest version of serenity-jbehave.
