### ISSUE TITLE
JUnit strange bheaviour

### ISSUE THREAD

**Issue by maforast** [serenity-bdd/serenity-jbehave#148]
As you can see I write 5 stories, that are associated to 5 different Java class. Every story have same name of stories file but in Camel Case. I think you have used reflection.

So, I expected only one story for each unit test and not all stories was repeated for eache unit test.

Can you tell me where I have mistake?

Tnx

**Comment by wakaleo** [comment]
The Serenity Runner uses reflection based on story names by default, so assumes that story names are unique (which they generally should be).

**Comment by maforast** [comment]
Yes all my story name are unique and are in camel case with java class that extend SerenityStories.

But as you can see my story are all repeated, in Junit test, for every java class.

Is there a configuration or a error that cause this ?

**Comment by wakaleo** [comment]
I couldn't say without seeing the project itself.

**Comment by maforast** [comment]
![tests](https://user-images.githubusercontent.com/15627875/34051692-e2050cae-e1bf-11e7-85d3-a10bc22c1d08.png)

This is project

**Comment by wakaleo** [comment]
Do the test classes extend SerenityStories or SerenityStory?

**Comment by maforast** [comment]
Ofcourse

**Comment by wakaleo** [comment]
I mean -which one. SerenityStories will run all the stories it can find (subject to the filters you configure), whereas SerenityStory will match the name.

**Comment by maforast** [comment]
Every class under discard pkg that match story filename, in my code extends SerenityStory do you inteed this?

**Comment by wakaleo** [comment]
Yes, that is correct

**Comment by maforast** [comment]
So I don't understand what is wrong. My configuration is the same.

**Comment by wakaleo** [comment]
In that case your best bet is to put a breakpoint in the SerenityStory class and see where it is loading the story files from.

**Comment by maforast** [comment]
Ok All work well with SerenityStory extends.
