### ISSUE TITLE
Sending Reports on email from jenkins

### ISSUE THREAD

**Issue by murthysp** [serenity-bdd/serenity-jbehave#152]
I am running my serenity tests on Jenkins and want to send out the report through email. Any help would really appreciate.

**Comment by wakaleo** [comment]
This is a usage question (more Jenkins than Serenity), so it would be better to ask it on the Serenity Groups or the Serenity chat channels (http://serenity-bdd.rocket.chat)

**Comment by murthysp** [comment]
Thanks Wakaleo
