### ISSUE TITLE
JBehave Lifecycle/Background is working with serenity

### ISSUE THREAD

**Issue by samangipudi** [serenity-bdd/serenity-jbehave#155]
I'm using Serenity core - 1.5.11 and Serenity-jBehave -1.18.0.
Story file is not able to detect Lifecycle or Background. It is Just considering as a normal text and skipping

**Comment by wakaleo** [comment]
Try with the latest version.

**Comment by samangipudi** [comment]
I cannot switch to the latest version. Any version after 1.5.11 is ending up with an initialization failure. I can down the version, If you can say with what other version it works.

**Comment by wakaleo** [comment]
What failure are you getting?

**Comment by wakaleo** [comment]
I believe support for lifecycle and backgrounds came in a more recent version of JBehave than the one used in 1.5.11, so you will need to upgrade.

**Comment by wakaleo** [comment]
Closing this as this feature is supported in the latest version of Serenity - feel free to reopen if you have an issue with the latest version.
