### ISSUE TITLE
Story missing in the report if it fails/throws exception in @BeforeStory method

### ISSUE THREAD

**Issue by nikolaykolev** [serenity-bdd/serenity-jbehave#16]
If a story has @BeforeStory and it throws an exception in the before story method it does not show in the report at all. I'm building with maven, serenity version 1.1.2. (It's not duplicate with #13 ) There was an exception in my case but it's not connected to the issue I think. I can post it if needed.

**Comment by YamStranger** [comment]
Hello @nikolaykolev. Thanks for this issue!!!
I will close this issue as duplicate to #13, and all fixes will be provided under #13.  Exception in #13 is the reason why report does not appear in your serenity report. 

Thanks for helping us making Serenity BDD better!

**Comment by nikolaykolev** [comment]
Thank you ! :)
