### ISSUE TITLE
jbehave data table and Lifecyle

### ISSUE THREAD

**Issue by mmanach** [serenity-bdd/serenity-jbehave#166]
Hello, 

I think it's propably a jbehave issue, but want to be sure : 

I try to use the 
```
Example:
data/testdata.table
```
to externalize my test data

Two remarks : 
- Steps in Lifecyle:Before don't take parameter from Example:table
```
Lifecycle:
Before:
When fill email <login> and password <pwd> and validate
```
Knowing that login and pwd are declared in the testdata.table, the test will write "< login >" and "< pwd >" for the Before's step. For Scenario's step, it works.

- If you have 3 scenarios with the same parameters in one story file, it's mandatory to add the Example:table after each scenario... So it's not allowed to declare the table only once. Quite redundant. 😥

**Comment by mmanach** [comment]
Ok, so it's an opened bug from jbehave... since 2014. And not fixed yet...
https://jbehave.atlassian.net/browse/JBEHAVE-1006

**Comment by wakaleo** [comment]
Thanks for the update - I’ll close this issue for now then.

**Comment by wakaleo** [comment]
Including a table that way looks like a BDD antipattern to me, though - you can’t see what the examples are, so the scenario has limited use as living documentation
