### ISSUE TITLE
Run same story multiple times by setting iterations using a single meta tag

### ISSUE THREAD

**Issue by push2212** [serenity-bdd/serenity-jbehave#168]
Hi,
I have a requirement ,where I need to execute a same story multiple times with different values each time.
I need to execute the same story for eg, 100 times , however do not want to specify the number of iterations in the goal , viz. by mentioning the respective tag 100 times in the goal.
Is there any other way where I can set the iterations and pass multiple values to a single story?
Could you please help here.

**Comment by wakaleo** [comment]
JBehave (or Cucumber) Is a living documentation tool, not a test scripting tool, so it is not designed for this sort of thing. You can either use dynamically generated data at the step def level (e.g. "Given 100 high risk customers") or pass in numbers in the action steps (e.g. "When 100 users attempt to view an item in the catalog"), but if you want to provide a set of 100 external data points, it would be better to use JUnit.
