### ISSUE TITLE
story duplicated in report home if story title differs from filename

### ISSUE THREAD

**Issue by robertzett** [serenity-bdd/serenity-jbehave#17]
If the story title (first line in .story file) differs from the filename then it will appear twice in the report home page. One being named by the title and the second being derived from the filename. The second one then will be a dead link.
Been able to reproduce with serenity jbehave maven archetype changing the title of the story "LookupADefinition.story" to something else than "Lookup a definition".
Tested with serenity-core 1.1.9 and 1.1.6, serenity-maven-plugin 1.1.7 and 1.1.6, serenity-jbehave 1.1.0

**Comment by f1r3ok** [comment]
Same thing for me either.
I've tried using the latest (1.1.24 and 1.1.25-rc.2) builds of the serenity-bdd:    
		<serenity.core.version>1.1.25-rc.2</serenity.core.version>
		<serenity.jbehave.version>1.5.0</serenity.jbehave.version>
		<serenity.junit.version>1.1.25-rc.2</serenity.junit.version>
		<serenity.maven-plugin.version>1.1.25-rc.2</serenity.maven-plugin.version>    
And the same issue with story namings.
Hope it can be helpful.
Thanks,
Philip Levin.

**Comment by wakaleo** [comment]
Thanks for these details. This is a known issue and is in our backlog.

On 18 January 2016 at 12:02, f1r3ok <notifications@github.com> wrote:

> Same thing for me either.
> I've tried using the latest (1.1.24 and 1.1.25-rc.2) builds of the
> serenity-bdd:
>
> 1.1.25-rc.2
> 1.5.0
> 1.1.25-rc.2
> 1.1.25-rc.2
>
> And the same issue with story namings.
> Hope it can be helpful.
> Thanks,
> Philip Levin.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serenity-bdd/serenity-jbehave/issues/17#issuecomment-172510401>
> .
>



-- 
___________________________________________________
John Smart | Wakaleo Consulting  |  +44 7497151337
Making smart teams collaborate better
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________

We love breaking down silos and helping smart teams collaborate better! Ask
about our tailored on-site workshops in *Agile Requirements Discovery
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Behaviour
Driven Development
<http://wakaleo.com/training/advanced-agile-requirements-workshop>*, *Agile
Development Practices
<http://wakaleo.com/training/testing-and-tdd-for-java-developers>*, and *Test
Automation
<http://wakaleo.com/training/automated-web-testing-with-webdriver-and-thucydides>*
!
___________________________________________________

**Comment by cliviu** [comment]
hi @robertzett . For the moment please set the property "use.test.case.for.story.tag = false", please let me know if is solves your problem.

**Comment by robertzett** [comment]
Hi @cliviu . Yes that property solves my issue. Did not know about that. Thanks!
Happy to see that property changed to be the default now.
sorry that it took me that long to test this

**Comment by cliviu** [comment]
hi @robertzett . That property will help only for the JBehave stories.  With JUnit tests it will not generate the correct outcome. We are working at fixing this by storing in the test outcomes the test source (junit/jbehave/cucumber) so we can use different tagging strategies depending on the test source.

**Comment by RazvanB2** [comment]
Hi @cliviu, 
   I had a problem with the features appearing twice in the reports. It seems that the property -Duse.test.case.for.story.tag=false worked for me as well. I had the same name for the file and for the feature so that wasn't my problem. Can you please explain in a couple of words what most likely is the problem?
I thought it has something to do with reading requirements folder twice: once the root and then every child:
[INFO] Loading requirements from isExists=true path:C:\Users\boteraz\Serenity\serenity-maven-archetypes-master\SerenityAndCucumberProj\src\test\resources\features
[INFO] Loading requirements from isExists=true path:C:\Users\boteraz\Serenity\serenity-maven-archetypes-master\SerenityAndCucumberProj\src\test\resources\features\PenetrationTesting

Thank you,
  Razvan

**Comment by cliviu** [comment]
Hi Razvan,
  setting   -Duse.test.case.for.story.tag=false is just a workaround for the moment. We will fix this in the next version, I will let you know. After the last changes we have the possibility now to identify the source of a test outcome (junit/cucumber/jbehave) and to choose the right strategy for reporting.

**Comment by wakaleo** [comment]
Fixed in 1.2.1-rc.8 onwards
