### ISSUE TITLE
gradle.build Grgit.open() deprecated ?

### ISSUE THREAD

**Issue by mithuns** [serenity-bdd/serenity-jbehave#170]
I tried importing the project in eclipse and was not able to do so. 
Did some google search and found the line no 17 in build.gradle is deprecated.
Please see here 
https://github.com/ajoberstar/grgit/issues/140

But, when I changed this line https://github.com/serenity-bdd/serenity-jbehave/blob/master/build.gradle#L17 to 
`grgit = Grgit.open(currentDir: file('.'))`
It worked just fine. 
Also, when we are at this.
Can we also update the grgit version to any of the more recent versions ?

**Comment by wakaleo** [comment]
Sure, any PRs are welcome.
