### ISSUE TITLE
Permission denied for gradlew

### ISSUE THREAD

**Issue by mithuns** [serenity-bdd/serenity-jbehave#173]
I was trying to do a build on travis-ci, but it wont go beyond the first step and kept complaining about permission denied for gradlew.
`/home/travis/.travis/job_stages: line 236: ./gradlew: Permission denied`
So, I added this line to .travis.yml and it fixed the problem.
`- chmod +x gradlew`

This one task is still missing though
`Task 'integrationTests' not found in root project 'serenity-jbehave'.`

Not sure , if thats something yet to be implemented or it just does not apply here ? 

I can do a PR , if this seems okay ?

**Comment by mithuns** [comment]
Without the chmod +x for gradlew
https://travis-ci.org/mithuns/serenity-jbehave/builds/347602548
After the chmod +x for gradlew
https://travis-ci.org/mithuns/serenity-jbehave/builds/347605880

**Comment by mithuns** [comment]
`Task 'browserTests' not found in root project 'serenity-jbehave'.`
https://travis-ci.org/mithuns/serenity-jbehave/builds/347609238

**Comment by wakaleo** [comment]
For serenity-jbehave, all the tests are executed via "gradle test".

**Comment by wakaleo** [comment]
Also, you might have more luck but I have found that travis-ci and the other SAAS CI platforms don't have the capacity to run a serenity build reliably.

**Comment by mithuns** [comment]
I am sorry, I think I may have conflated two things together, the `chmod +x gradlew` was needed just to make it build, then tests are missing is the second question, for the first part I can do a PR, if needed, and for the second part, I am seeking more information.

**Comment by wakaleo** [comment]
For the tests, all the tests get run with gradle test, the other tasks don’t exist for thisnproject

**Comment by mithuns** [comment]
Thank you. I will do a PR for the first part of my question. We can close this.
