### ISSUE TITLE
Upgrade org.reflections dependency to newer version

### ISSUE THREAD

**Issue by john236** [serenity-bdd/serenity-jbehave#18]
I'm having some problems with java 8 because serenity-jbehave is transitively depending on an old version of javassist.  According to mvn dependency:tree :

    [INFO] +- net.serenity-bdd:serenity-jbehave:jar:1.1.0:test
    [INFO] |  +- org.reflections:reflections:jar:0.9.8:test
    [INFO] |  |  +- javassist:javassist:jar:3.12.1.GA:test

Please upgrade the org.reflections dependency to 0.9.9 or later.

**Comment by YamStranger** [comment]
Dependent on #19

**Comment by YamStranger** [comment]
Hi @john236 requested update available under [jbehave 1.5.0](https://github.com/serenity-bdd/serenity-jbehave/releases/tag/v1.5.0)

If you fell that this issue already fixed please close this issue
