### ISSUE TITLE
Testing SOAP webservice using Serenity jbehave

### ISSUE THREAD

**Issue by dan0935** [serenity-bdd/serenity-jbehave#201]
I need to test SOAP webservice using Serenity jbehave. Can anyone help me out how to test that?

**Comment by jayzsuarez** [comment]
@dan0935  Kindly look this article.

https://spring.io/guides/gs/consuming-web-service/

**Comment by wakaleo** [comment]
There is no special support in Serenity for SOAP but you can write your own Screenplay Abilities or action classes using the techniques mentioned by @jayzsuarez.
