### ISSUE TITLE
AutoIT with Serenity BDD- jBehave - Compilation error

### ISSUE THREAD

**Issue by push2212** [serenity-bdd/serenity-jbehave#202]
Hi,

I am trying to use AutoIT in Serenity BDD framework. I am getting compilation error package does not exist -cannot find symbol even though all the required jars and dll's are present and set up.
-------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] C:\OpenUI-SJBAutomationExecution\src\main\java\pages\LoginPage.java:[3,0] error: package autoitx4java does not exist
[ERROR] C:\OpenUI-SJBAutomationExecution\src\main\java\pages\LoginPage.java:[4,20] error: package com.jacob.com does not exist
[ERROR] C:\OpenUI-SJBAutomationExecution\src\main\java\pages\LoginPage.java:[88,21] error: cannot find symbol
[ERROR]   symbol:   variable LibraryLoader
  location: class LoginPage
C:\OpenUI-SJBAutomationExecution\src\main\java\pages\LoginPage.java:[90,2] error: cannot find symbol
[ERROR]   symbol:   class AutoItX
  location: class LoginPage
C:\OpenUI-SJBAutomationExecution\src\main\java\pages\LoginPage.java:[90,18] error: cannot find symbol

Could you please help here.

**Comment by wakaleo** [comment]
A compilation error indicates a missing dependency in your pom file. As it is not a defect as such, could you post this on https://serenity-bdd.rocket.chat (to ask help from community members) or, if a quicker response is important), open a support ticket from one of our commercial support packages (https://johnfergusonsmart.com/serenity-bdd-mentoring/#support).

**Comment by push2212** [comment]
I added a dependency for jacob , however , could not find it for autoitx4java . will surely post the query in the mentioned groups . Thanks John.
