### ISSUE TITLE
Need help in enable and disable proxy setting in IE for Serenity BDD Framework through code

### ISSUE THREAD

**Issue by ShubhamSerenity** [serenity-bdd/serenity-jbehave#203]
Hi,
Need help in enable the proxy setting "xxxxx:1999" in IE browser and disable after running few lines of code.
Can you please help to resolve this issue.

Regards
Shubham Rastogi

**Comment by wakaleo** [comment]
Can you do this in pure WebDriver? It sounds like a Selenium question rather than a Serenity one.

**Comment by ShubhamSerenity** [comment]
Thanks
