### ISSUE TITLE
Want to fetch Meta tags and stories from external text file

### ISSUE THREAD

**Issue by push2212** [serenity-bdd/serenity-jbehave#204]
Hi,

I have almost 1500 stories developed in Serenity BDD with jBehave. I want Serenity to fetch only the Stories which i want to run with tags, from an external text file rather than being a part of the serenity framework.
Currently, even if I have to run a single story , Serenity compiles all the 1500 and takes too much time to run.
Could you please suggest how can I implement this.

**Comment by wakaleo** [comment]
This is due to a design defect in JBehave, and can’t be fixed (we have implemented some workarounds but the fundamental flaw in JBehave remains). For late project I would recommend migrating to Cucumber
