### ISSUE TITLE
How can we run a proxy setting command in CMD by the help of Serenity BDD Framework.

### ISSUE THREAD

**Issue by ShubhamSerenity** [serenity-bdd/serenity-jbehave#206]
Hi,
Need help in running proxy setting command in CMD with authentication and after running the code, need to disable it.
command : "node proxy-login-automator.js -local_port 8081 -remote_host xxxxx -remote_port 1999 -usr USERNAME -pwd PASSWORD".

Regards
Shubham

**Comment by wakaleo** [comment]
This is a Selenium question I think, and I suspect you would need to create a new driver without the proxy settings manually.

**Comment by ShubhamSerenity** [comment]
Thanks for the input.
