### ISSUE TITLE
How to connect appium with Serenity BDD Framework?

### ISSUE THREAD

**Issue by ShubhamSerenity** [serenity-bdd/serenity-jbehave#207]
I need to connect **Appium** Mobile testing framework with **Serenity BDD framework**.
I need to execute script for both mobile and web.
Can you please provide the steps for connecting Appium with Serenity BDD Framework.

Regards
Shubham

**Comment by wakaleo** [comment]
As this is a question and not a defect, could you ask it on the https://serenity-bdd.rocket.chat channel instead?
