### ISSUE TITLE
Could not able to see graph on serenity report 

### ISSUE THREAD

**Issue by sonaliarjun** [serenity-bdd/serenity-jbehave#208]
When I open index.html I see a report but could not able to see the graph. Also the report view is different than the default one. I am new to this and don't understand what is the problem. This is the [screenshot ](https://drive.google.com/file/d/1tDDzZ5jDGgPO6Clp5mwl08nh48pmtLwb/view?usp=sharing)for the report.

**Comment by wakaleo** [comment]
Are you using the latest version?

**Comment by sonaliarjun** [comment]
yes this is my pom file 
[pom.txt
](https://drive.google.com/file/d/12EJX9NiBBqRanhdYP1eZUF0JE76k09zc/view?usp=sharing)

**Comment by wakaleo** [comment]
Can you provide a sample project?

**Comment by sonaliarjun** [comment]
You can find it [here](https://drive.google.com/drive/folders/1aVHOCA-tdn0q5Dtf3ocIedyqPIw0gF4Q?usp=sharing)

**Comment by wakaleo** [comment]
I can't reproduce the issue with the project you provided. But the story files should be in `src/test/resources/stories`, and serenity-maven-plugin should be the same version as core.

**Comment by sonaliarjun** [comment]
hmm, that's weird. I changed it and now it looks like [this](https://drive.google.com/file/d/1oh1FtDeJvQzm4JudYCyivXYZ272G7EQO/view?usp=sharing) but still not the default view.

**Comment by wakaleo** [comment]
This is the new report design in Serenity 2.0.x

**Comment by sonaliarjun** [comment]
Thank you for your help 🥇 Have a nice day
