### ISSUE TITLE
How do I set page URLs?

### ISSUE THREAD

**Issue by pushprajsingh05** [serenity-bdd/serenity-jbehave#211]
I have set baseURL in `serenity.properties` file as

`webdriver.base.url = https://demo-stage.com/`

now in LoginPage.java URL will be = baseURL+"/login.html"
now in ProfilePage.java URL will be = baseURL+"/myProfile.html"

How to achieve this?

**Comment by wakaleo** [comment]
Just use @DefaultUrl("login.html") for LoginPage and @DefaultUrl("myProfile.html") for the ProfilePage.

See https://serenity-bdd.github.io/theserenitybook/latest/page-objects.html#_opening_the_page.

**Comment by pushprajsingh05** [comment]
I just tested it passed. Thanks

Last query
How can I call this base.Url is my scripts, for concatenation purpose?
```
String expectedPageURL = getDriver().cureentPageURL();
String actualURL = $("base.Url")+getUserID()+"/"+getUTMs();
assertTrue(expectedPageURL.contains(actualURL));
```

**Comment by wakaleo** [comment]
Something like this will retrieve the WebDriver base URL from your environment properties:

```
    EnvironmentVariables environmentVariables;
        ...
        String baseUrl = ThucydidesSystemProperty.WEBDRIVER_BASE_URL.from(environmentVariables);
```

**Comment by pushprajsingh05** [comment]
I will define String baseURL in BaseClass.java. So,:
1. Do I get "ThucydidesSystemProperty" intialised already.

**Comment by wakaleo** [comment]
Serenity should inject the environmentVariables field into your page object (as long as you extend the Serenity PageObject class). `ThucydidesSystemProperty.WEBDRIVER_BASE_URL` is an enum value. The code shown here should be enough.

**Comment by pushprajsingh05** [comment]
I have defined it like below ,

```
public class BasePage extends PageObject {
    public static Date date;
    public static SimpleDateFormat simpleDateFormat;
    private net.thucydides.core.util.EnvironmentVariables environmentVariables;
   String baseUrl = ThucydidesSystemProperty.WEBDRIVER_BASE_URL.from(environmentVariables);

__
}
```

 but it is giving me error.
`(net.serenitybdd.core.exceptions.StepInitialisationException: Failed to create step library for EndUserSteps:java.lang.NullPointerException-->null)`

**Comment by pushprajsingh05** [comment]
It worked.

Last query before I close this thread.

How do I concatenate baseURL and pageURL?

String expectedURL = getBaseURL()+getProfilePageURL()+"/"+username; like this

**Comment by wakaleo** [comment]
There isn't a simple api to get the overall page url.

**Comment by pushprajsingh05** [comment]
I can create a method in ProfilePageClass which will return default URl of that page.

public String loginPageURL(){
return ____ ;
}

do you mean such method is not possible?

**Comment by wakaleo** [comment]
That is correct; there are many other ways of defining a pages URL beyond the DefaultUrl annotation.

**Comment by pushprajsingh05** [comment]
Thanks @wakaleo , all queries are resolved, except the logging query in HTML reports. I will open separate ticket for it.
