### ISSUE TITLE
Stubborn .svg files in /target/site/serenity/.../../../.svg

### ISSUE THREAD

**Issue by pushprajsingh05** [serenity-bdd/serenity-jbehave#214]
It happens on the intermittent basis that clean task fails, due to below error.

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-clean-plugin:2.5:clean (default-clean) on project demo-automation-tests: Failed to clean project: Failed to delete src\tests\target\site\serenity\fontawesome-free-5.3.1-web\svgs\solid\tty.svg -> [Help 1]`

When dig deep it was found the explorer.exe on windows is using this file. Only way to clean up is restart system in Safe Mode and delete it.

If you attempt to stop explorer.exe and type `rm -f /../. ____ .svg` it will again give error. Tried with admin access also.

**Comment by wakaleo** [comment]
This is useful information but I'm not sure what Serenity could do about Windows Explorer locking file access (presumably if you already have the report open in Windows Explorer).

**Comment by pushprajsingh05** [comment]
I have been using regular non BDD maven framework with XSLT reports. During those times I have never faced such problem.

I understand that Serenity has nothing to do with it and perhaps it wont be a problem on Linux server, but do you suggest a workaround to get rid of it. 

Restarting system is very hectic.

**Comment by wakaleo** [comment]
It generally is never a problem on Linux, it is a very Window-specific issue, but I don't know any particular workaround.

**Comment by pushprajsingh05** [comment]
Thanks @wakaleo closing this. Irrelevant question, it was.
