### ISSUE TITLE
I want to create range slider in serenity for rating 

### ISSUE THREAD

**Issue by Rajendra1002** [serenity-bdd/serenity-jbehave#234]

**Comment by Rajendra1002** [comment]
Please reffere this link to know what exactly in want to..

https://www.w3schools.com/HOWTO/howto_js_rangeslider.asp

**Comment by wakaleo** [comment]
Could you be more clear as to what you are trying to do?

**Comment by Rajendra1002** [comment]
![Range_slider_for_volume_rating](https://user-images.githubusercontent.com/58292313/69944518-864a5d00-150d-11ea-9a0e-559f30a7c247.jpg)

pelase check aatached img ...

**Comment by Rajendra1002** [comment]
Hi,

Used 
[StaticTextBlock(HideLabel = true, IsHtml = true, IsLocalText = false, Text = "<input type='range' value='CommunicationSkillRating' min='1' max='10' class='slider' id='ratingvalue'>")]
        public Int32 ratingvalue { get; set; }
