### ISSUE TITLE
Hanging/Crashing when using Jbehave expressions on Story file

### ISSUE THREAD

**Issue by edricklacbayo** [serenity-bdd/serenity-jbehave#243]
![image](https://user-images.githubusercontent.com/28752767/80665350-d08b3680-8acb-11ea-81bd-9e935a6d70a2.png)

There are times that when I try to replace JBehave expressions on story file. It crashes.

**Comment by edricklacbayo** [comment]
![image](https://user-images.githubusercontent.com/28752767/80957095-10884b80-8e35-11ea-975e-65e13c91b6bd.png)
 Also when typing on the Story file

**Comment by wakaleo** [comment]
I don’t think this is related to Serenity, it looks more like an IntelliJ issue.
