### ISSUE TITLE
Please put version 1.47.0 to maven central

### ISSUE THREAD

**Issue by hrotkogabor** [serenity-bdd/serenity-jbehave#244]
As of now, the latest artifact version in central maven repo is:
```
<dependency>
  <groupId>net.serenity-bdd</groupId>
  <artifactId>serenity-jbehave</artifactId>
  <version>1.46.0</version>
</dependency>
```
, but the latest release is 1.47.0
Please put the latest release to the central maven repo.

**Comment by wakaleo** [comment]
That is an error, the latest version is 1.46.0

**Comment by hrotkogabor** [comment]
But on this page: https://github.com/serenity-bdd/serenity-jbehave/releases
the latest version is 1.47.0 created on on May 23 2019.

**Comment by wakaleo** [comment]
It’s an error on the page

**Comment by hrotkogabor** [comment]
And when can we expect 1.47.0 to be released?

**Comment by wakaleo** [comment]
There's nothing in 1.0.47, so there is nothing to release. We are only doing minimal maintenance on this module.
