### ISSUE TITLE
Test ignored if comment exists in Gherkin feature file

### ISSUE THREAD

**Issue by uamainacademy** [serenity-bdd/serenity-jbehave#246]
Hello every one. I have an issue in last version of serenity 2.3.6.

If I add comment into my feature file, test become ignored in report. Before 2.3.6 I used 2.0.71 version, and everything was ok.

Is there are any solution which can fix this?

Thanks.

![serenity_1](https://user-images.githubusercontent.com/70111429/97411349-d0e47d00-1908-11eb-9fd1-30f84f752f57.png)
![serenity_2](https://user-images.githubusercontent.com/70111429/97411358-d346d700-1908-11eb-927b-7092dafae74c.png)

**Comment by wakaleo** [comment]
We are not actively supporting JBehave beyond versions 2.1.x and higher.

**Comment by uamainacademy** [comment]
Ok, thanks for quick response. I will downgrade to 2.0.71 version back.
