### ISSUE TITLE
Please push to maven latest version - 1.47

### ISSUE THREAD

**Issue by mykolap** [serenity-bdd/serenity-jbehave#248]
It is released 1.5 years ago, but still not published

**Comment by wakaleo** [comment]
JBehave is not supported with the latest versions of Serenity.

**Comment by mykolap** [comment]
But there is released version, but it is not published to maven. Can you publish it, please. I am not asking for releasing new versions, only for publish already released.

**Comment by wakaleo** [comment]
The latest code is already released in version 1.46

**Comment by mykolap** [comment]
I see that in version 1.47 - jbehave runner 2.3.0 and jbehave core 4.5
In version 1.46 - runner 2.2.0 and jbehave core 4.4
I cannot just update those libs, because of incompartibiity, in 1.47 it is already updated

Why I want to try new version - maybe it can help with issue:
Execution failed for task ':test'.
> Received a completed event for test with unknown id '1.594'. Registered test ids: '[1.1, 1.595, 1.597, 1.598, 1.601, :test]'
that we are facing...

**Comment by wakaleo** [comment]
Where do you see a version 1.47? The latest version is 1.46. Beyond this the test suite fails and we don't have any plans to work on this code in the near future, but you are welcome to take a look.

**Comment by mykolap** [comment]
Here: https://github.com/serenity-bdd/serenity-jbehave/releases
Sorry, I thought it was released, but not pushed to maven.
Thank you very much for answers, question can be closed.
