### ISSUE TITLE
@BeforeScenario or @BeforeScenario(uponType = ScenarioType.ANY) did not work

### ISSUE THREAD

**Issue by JungPham** [serenity-bdd/serenity-jbehave#256]
Hi guys, I tried with @BeforeScenario or @BeforeScenario(uponType = ScenarioType.ANY) before a public method but this method didn't run before each scenario, my version <jbehave-core.version>4.1</jbehave-core.version>. Any one can help me? I am so grateful if anyone can help me.

**Comment by JungPham** [comment]
Solved

**Comment by wakaleo** [comment]
Is this not a JBehave issue/question?
