### ISSUE TITLE
Question. JBehave, Serenity 3+ and Selenium4

### ISSUE THREAD

**Issue by kavy24** [serenity-bdd/serenity-jbehave#258]
Hi, just a quick question to enquire if JBehave, Serenity 3+ and selenium 4 are compatible as been having challenges getting them to work together. Thanks

**Comment by wakaleo** [comment]
JBehave support is not actively maintained - we recommend using Cucumber instead.

**Comment by kavy24** [comment]
Thank you for your reply. Regards R
