### ISSUE TITLE
ArrayIndexOutOfBoundsException when using serenity-jbehave with Java 8 lambda

### ISSUE THREAD

**Issue by richard-melvin** [serenity-bdd/serenity-jbehave#30]
If you define JBehave @Steps in a file that contains a java 8 lambda, you will get a run-time exception of the form:

```
java.lang.ArrayIndexOutOfBoundsException: 29539
               at com.thoughtworks.paranamer.BytecodeReadingParanamer$ClassReader.accept(BytecodeReadingParanamer.java:554)
               at com.thoughtworks.paranamer.BytecodeReadingParanamer$ClassReader.access$200(BytecodeReadingParanamer.java:337)
               at com.thoughtworks.paranamer.BytecodeReadingParanamer.lookupParameterNames(BytecodeReadingParanamer.java:102)
               at com.thoughtworks.paranamer.CachingParanamer.lookupParameterNames(CachingParanamer.java:75)
               at org.jbehave.core.steps.StepCreator.paranamerParameterNames(StepCreator.java:197)
               at org.jbehave.core.steps.StepCreator.parameterNames(StepCreator.java:134)
               at org.jbehave.core.steps.StepCreator.access$900(StepCreator.java:36)
```

This is due to [this](https://github.com/paul-hammant/paranamer/issues/17) issue with the paranamer library used by jbehave.

Any code such as:

```java
	  Supplier<Boolean> isTrue = () -> true;
```

anywhere in a file that contains a `@Given/When/Then` annotation seems enough to trigger the problem.

Note that while Jbehave has paranamer turned off by default, serenity-jbehave turns it on in SerenityJBehave.defaultConfiguration.

To resolve, the version of paranamer and/or jbehave used would presumably need to be upgraded to one with the bug fixed.

**Comment by YamStranger** [comment]
Hello @richard-melvin 

For now updating to jbehave 4.0.+ can not be done (but it will be done soon). So paranamer was updated to use com.thoughtworks.paranamer:paranamer:2.7  - as you recommended. 

>To resolve, the version of paranamer and/or jbehave used would presumably need to be upgraded to one with the bug fixed.

Please close this issue, if your problem is solved. 

Thanks a lot!!!

**Comment by YamStranger** [comment]
It seems that this issue already solved or not an issue any more

**Comment by richard-melvin** [comment]
sort of - the fix looks ok, but the release containing it is not available as a library to easily test (1.6 seems to be missing on maven central).

**Comment by YamStranger** [comment]
Hello @richard-melvin please try to use bintray instead of maven central:
```
   <repositories>
      <repository>
        <snapshots>
        <enabled>false</enabled>
        </snapshots>
        <id>central</id>
        <name>bintray</name>
        <url>http://jcenter.bintray.com</url>
      </repository>
    </repositories>
    <pluginRepositories>
      <pluginRepository>
        <snapshots>
        <enabled>false</enabled>
        </snapshots>
        <id>central</id>
        <name>bintray-plugins</name>
        <url>http://jcenter.bintray.com</url>
      </pluginRepository>
    </pluginRepositories>
```

**Comment by richard-melvin** [comment]
ok that works.

**Comment by YamStranger** [comment]
@richard-melvin Thanks for helping us make Serenity BDD better!!!

**Comment by flaz14** [comment]
I just would like to add that version 2.7 of `com.thoughtworks.paranamer:paranamer` doesn't solve the issue (may be it also depends on certain versions of *Serenity* and *JDK*...). I use version **2.8**. So the corresponding piece of POM looks like this:

```[xml]
    <dependency>
      <groupId>net.serenity-bdd</groupId>
      <artifactId>serenity-jbehave</artifactId>
      <version>1.0.18</version>
      <scope>test</scope>
      <exclusions>
        <exclusion>
          <groupId>com.thoughtworks.paranamer</groupId>
          <artifactId>paranamer</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>com.thoughtworks.paranamer</groupId>
      <artifactId>paranamer</artifactId>
      <version>2.8</version>
      <scope>test</scope>
    </dependency>
```

**Comment by wakaleo** [comment]
That is a *very* old version of serenity-jbehave.
