### ISSUE TITLE
Incorrect alignment of index.html file when story title is too long

### ISSUE THREAD

**Issue by anujbajaj** [serenity-bdd/serenity-jbehave#39]
Hi Team,

We are using Serenity 1.1.26 version & have been seeing an issue with the report file when we have a long story title in the story file. The table in the index.html file is getting dragged to the right till the length of story title even though there is a newline in it.

Please note that we have tried the same thing with Thucydides as well & didn't face this issue.

Attached are the files for your reference,

Thanks.

![samplestory](https://cloud.githubusercontent.com/assets/13576728/13125450/37830dc2-d58b-11e5-94db-948f26731e0a.png)
![storytitle](https://cloud.githubusercontent.com/assets/13576728/13125379/e3b81750-d58a-11e5-85ec-650aacfcf0b8.png)

**Comment by YamStranger** [comment]
Tanks @anujbajaj !

**Comment by wakaleo** [comment]
This will be fixed in version 1.1.32 of core.

**Comment by wakaleo** [comment]
Fixed in 1.1.33
