### ISSUE TITLE
JBehave Lifecycle support is needed

### ISSUE THREAD

**Issue by vgarmash** [serenity-bdd/serenity-jbehave#42]
Hello. I used Junit+JBehave before and now trying to integrate Serenity into the mix.
Nowhere in your documentation I can find examples about JBehave lifecycle support (http://jbehave.org/reference/stable/story-syntax.html, look for "Lifecycle:" or "Background").

Sometimes it is very useful to have Before and After steps to be executed around each scenario.

I tried to use:

```
Lifecycle:
After:
When <condition>
Then <action>
```

Serenity engine triggers those steps but the report shows them in wrong place.

It would be great if you add some samples how lifecycle steps should be implemented in Serenity with JBehave

**Comment by YamStranger** [comment]
Hello @vgarmash 

It seems usage of lifecycle does not display in reports property. 

Thanks

**Comment by wakaleo** [comment]
This should work in the next release.

**Comment by wakaleo** [comment]
This seems to work in 1.1.11.
