### ISSUE TITLE
Meta: @manual is not working

### ISSUE THREAD

**Issue by vgarmash** [serenity-bdd/serenity-jbehave#43]
Manual steps mentioned differently in different documentarians. In official documentation we read this:

> Row Manual contains manual tests, to do test manual you should use @Manual annotation, idea the same as for Automated row.

At [this blog](http://thucydides-webtests.com/2015/07/27/serenity-1-1-is-out/) I found more info: 

> And in JBehave, use the @manual tag in the Meta: section of a scenario:
> 
> Scenario: Display social media links for a product
> Meta:
> @manual
> 
> Given I have searched for 'Docking station' in my region
> When I select item 1
> Then I should see social media links
> In all cases, the manual test appear in the reports as a special kind of “Pending” test, indicated by a special icon

I tried to add this into my JBehave story:
```
Scenario: Should respect standard look and feel
Meta:
@manual
Given I just logged in
Then The page should match current UI mockup
```
and nothing happened.

I also added couple empty steps into my JBehave class:
  ```
  @Given("I just logged in") @Manual
    public void justLeggedIn(){}

    @Then("The page should match current UI mockup") @Manual
    public void verifyLookAnFeel(){}
```
and nothing happened either.

Seems like this feature is not working.

**Comment by YamStranger** [comment]
Hello @vgarmash Checked it - yes, it seems that this feature is broken 

Thanks!

**Comment by YamStranger** [comment]
Hello @vgarmash I added several tests in jbehave to be sure that @manual works fine also I tested it against [test project](https://github.com/serenity-bdd/serenity-test-projects/tree/master/jbehave-tags) and all works fine. Here is screenshot: 
 
![image](https://cloud.githubusercontent.com/assets/1667699/13220676/0e24f9a6-d980-11e5-8c5a-d0362911d260.png)

Allso new enhancement was provided and in next version of jbehave will be possible mark as @manual all story (all scenarios in story file)

Please provide more, for now I can't reproduce your problem

If you solved this issue based on provided answer, please close this ticket

Thanks!!!!

**Comment by vgarmash** [comment]
It was broken in serenity-core 1.1.25, but fixed in 1.1.26. Thank you.

Now you need to update the documentation to show current version of the report screenshot as the old one had different icon for the manual test.

**Comment by YamStranger** [comment]
Thanks @vgarmash 

Sure it will be updated

**Comment by robyc1982** [comment]
Hi guys,

I'm trying to use @Manual annotation as well in serenity 1.1.31 and it seems not to work.
The tests that I'm trying to annotate are shown in the HTML report as Pending instead of Manual.

I'm trying something like:
@Test
@Manual
public void thisIsAManualTest() {}

@YamStranger can we reopen this? or should I create a new bug?

Thanks,
Robert.

**Comment by wakaleo** [comment]
Hey Robert,

Thanks for raising this, we'll take a look.

**Comment by YamStranger** [comment]
Hello @robyc1982 

This ticket about jbehave, if you face problem with Junit - please open ticket about that in serenity-core

**Comment by aquadrehz** [comment]
I found this issue **on cucumber when mark @manual at story level** (before Feature:) 
So I created as following
 - https://github.com/serenity-bdd/serenity-core/issues/630
