### ISSUE TITLE
Jbehave ignore meta provided on same line as word 'Meta'

### ISSUE THREAD

**Issue by YamStranger** [serenity-bdd/serenity-jbehave#56]
It seems that during parsing and analysing meta from story file tags provided with next style are ignored: 

```
Meta: @ignore
```

same can be reproduced on story and scenario levels. 
Based on jbehave manual - all should work fine: http://jbehave.org/reference/stable/meta-filtering.html

Some examples for issue tag provided on same line: 
![story_same_line](https://cloud.githubusercontent.com/assets/1667699/13452123/c842e4e6-e04d-11e5-841f-ce9c1772c8b9.png)

![stories_separ_line](https://cloud.githubusercontent.com/assets/1667699/13452124/c844ce78-e04d-11e5-9ac5-c012d0f5fea0.png)

Same reproduced with @ignore tag.

**Comment by wakaleo** [comment]
Works in 1.31.0
