### ISSUE TITLE
WebDriver init during all tests

### ISSUE THREAD

**Issue by YamStranger** [serenity-bdd/serenity-jbehave#70]
WebDriver init during all tests. 

Most likely that next line is reason for this issue 
https://github.com/serenity-bdd/serenity-jbehave/blob/master/src/main/java/net/serenitybdd/jbehave/SerenityReporter.java#L152

**Comment by wakaleo** [comment]
The @Managed driver is only for JUnit. ThucydidesWebDriverSupport.getDriver() should only create proxy drivers, not instantiated ones - the instantiated drivers should only be created when a method is called on the WebDriver proxy instance.

___________________________________________________
John Smart | Wakaleo Consulting  |  +44 7398 832273
Making smart teams collaborate better
http://www.wakaleo.com  |  john.smart@wakaleo.com
___________________________________________________


On 12 April 2016 at 9:53:02 PM, Yaroslav Pishta (notifications@github.com) wrote:

WebDriver init during all tests, even if they are not contains @Managed webdriver.

Most likely that next line is reason for this issue
https://github.com/serenity-bdd/serenity-jbehave/blob/master/src/main/java/net/serenitybdd/jbehave/SerenityReporter.java#L152

**Comment by YamStranger** [comment]
@wakaleo thanks

**Comment by YamStranger** [comment]
Issue fixed
