### ISSUE TITLE
Provide a way to do extra configuration before stories are executed

### ISSUE THREAD

**Issue by csabakoncz** [serenity-bdd/serenity-jbehave#82]
It would be nice if `SerenityStories` would have a chance to perform some extra configuring on `ConfigurableEmbedder` before `SerenityReportingRunner` invokes  `getConfiguredEmbedder().runStoriesAsPaths(getStoryPaths());`
in its `run()` method.

E.g. it could have a `beforeStoriesRun(ConfigurableEmbedder)` for this purpose.

This possibility would help me in configuring per-story timeouts which is possible since JBehave 4
(http://grepcode.com/file/repo1.maven.org/maven2/org.jbehave/jbehave-core/4.0.2/org/jbehave/core/embedder/StoryTimeouts.java#StoryTimeouts.asMap%28java.lang.String%29)

**Comment by wakaleo** [comment]
Fixed in 1.1.33 - you can overrider the beforeStoriesRun(ConfigurableEmbedder) method - thank's for the suggestion!
