### ISSUE TITLE
Skip tag not working when running SerenityStory

### ISSUE THREAD

**Issue by wakaleo** [serenity-bdd/serenity-jbehave#85]
Dear Serenity Support,

When running a JBehave story via a java class that extends SerenityStory, as a junit test, the @skip meta tag is being ignored. When running the same story via maven, with the serenity-aggregate profile, the @skip meta tag works.
This is inconsistent behaviour and we use the @skip meta tag extensively. Can you please investigate?

Sincerely,
Luka

**Comment by wakaleo** [comment]
Do you mean when you run the scenario from the IDE? If this is the case, it should be fixed in the next release.

**Comment by YamStranger** [comment]
@wakaleo I have investigated it:
@skip tag works fine when some build tool is used (gradle, maven), and did not works when such tests run with IDE

**Comment by wakaleo** [comment]
Appears to be working in 1.31.0.
