### ISSUE TITLE
How to access K-V pairs in serenity.properties?

### ISSUE THREAD

**Issue by im-zeeshan** [serenity-bdd/serenity-jbehave#94]
How do I access the key-value pairs specified in serenity.properties file inside java classes/methods?

I tried using `Serenity.getCurrentSession().get(key);`... but it does not have the required `keySet()`.

I have added an application specific property to serenity.properties file and want to access it during runtime.

For example: 
`myapp.some.key=C:\\some\\file\\path`

I also tried using `System.getProperty()` but it didn't work as well.

**Comment by YamStranger** [comment]
I am not sure that such sing can used right now. 
Do you need such feature?

**Comment by wakaleo** [comment]
Just add a field of type EnvironmentVariables

**Comment by YamStranger** [comment]
Will add it in documentation

**Comment by TanasescuAlexandru** [comment]
Try this:

String property = SerenitySystemProperties.getProperties().getValue(ThucydidesSystemProperty.WEBDRIVER_BASE_URL);

**Comment by nbarrett** [comment]
Or:

`EnvironmentVariables variables = SystemEnvironmentVariables.createEnvironmentVariables();`

`String baseUrl = variables.getProperty(ThucydidesSystemProperty.WEBDRIVER_BASE_URL);`
`String myCustomProperty = variables.getProperty("my.custom.property");`

**Comment by vikramvi** [comment]
@TanasescuAlexandru have you tried setting value for a property at runtime ?

**Comment by wakaleo** [comment]
Presuming answered.

**Comment by vikramvi** [comment]
worked as per solution mentioned by @nbarrett

**Comment by davidverdu** [comment]
```java
EnvironmentVariables variables = SystemEnvironmentVariables.createEnvironmentVariables();
String username = EnvironmentSpecificConfiguration.from(variables).getProperty("user.manager.username");
String password = EnvironmentSpecificConfiguration.from(variables).getProperty("user.manager.password");
String homepage = EnvironmentSpecificConfiguration.from(variables).getProperty("homepage.url");
```

**Comment by FernandoCotrena** [comment]
Hola david. Como tenes definidas en el archivo serenity.confi las variables user.manager.username, etc.. por que estoy intentando levantar esas properties pero obtengo nullpointer

**Comment by davidverdu** [comment]
The variables are defined per enviroment inside serenity.conf

environments {
   default {
      user.manager.username = "manager"
      user.manager.password = "secret"
   }

   dev {
      user.manager.username = "manager_dev"
      user.manager.password = "secret"
   }
  
 ...
}
